# .github/workflows/stale-branches.yml

name: Stale Branches

on:
  schedule:
    - cron: '0 13 * * 5'
    
permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v2.0.1
      with:
        repo-token: ${{ github.token }}
        compare-branches: 
          - 'info'
          - 'save'
        days-before-delete: 93
