# .github/workflows/stale-branches.yml

name: Stale Branches

on:
  schedule:
#     - cron: '0 21 * * 5'
    - cron: '* * * * *'
permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v2.0.1
      with:
        repo-token: ${{ github.token }}
        compare-branches: 'save'
        days-before-delete: 93
        days-before-stale: 62
        comment-updates: false
        max-issues: false
        tag-committer: false
        stale-branch-label: stale branch
